[package]
name = "vcbbcv"
version = "0.1.0"
authors = ["Nebula Venus <nebulavenus@tuta.io>"]
edition = "2018"

[dependencies]
glsp = "0.2.0"
macroquad = "0.3.0-alpha.15"

[profile.dev.package.'*']
opt-level = 3